# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yash/Documents/ImageRetrieval

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yash/Documents/ImageRetrieval

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yash/Documents/ImageRetrieval/CMakeFiles /home/yash/Documents/ImageRetrieval//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yash/Documents/ImageRetrieval/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named image_retrieval

# Build rule for target.
image_retrieval: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 image_retrieval
.PHONY : image_retrieval

# fast build rule for target.
image_retrieval/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_retrieval.dir/build.make CMakeFiles/image_retrieval.dir/build
.PHONY : image_retrieval/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_retrieval.dir/build.make CMakeFiles/image_retrieval.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_retrieval.dir/build.make CMakeFiles/image_retrieval.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_retrieval.dir/build.make CMakeFiles/image_retrieval.dir/main.cpp.s
.PHONY : main.cpp.s

src/distance_metrics.o: src/distance_metrics.cpp.o
.PHONY : src/distance_metrics.o

# target to build an object file
src/distance_metrics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_retrieval.dir/build.make CMakeFiles/image_retrieval.dir/src/distance_metrics.cpp.o
.PHONY : src/distance_metrics.cpp.o

src/distance_metrics.i: src/distance_metrics.cpp.i
.PHONY : src/distance_metrics.i

# target to preprocess a source file
src/distance_metrics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_retrieval.dir/build.make CMakeFiles/image_retrieval.dir/src/distance_metrics.cpp.i
.PHONY : src/distance_metrics.cpp.i

src/distance_metrics.s: src/distance_metrics.cpp.s
.PHONY : src/distance_metrics.s

# target to generate assembly for a file
src/distance_metrics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_retrieval.dir/build.make CMakeFiles/image_retrieval.dir/src/distance_metrics.cpp.s
.PHONY : src/distance_metrics.cpp.s

src/feature_extractor.o: src/feature_extractor.cpp.o
.PHONY : src/feature_extractor.o

# target to build an object file
src/feature_extractor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_retrieval.dir/build.make CMakeFiles/image_retrieval.dir/src/feature_extractor.cpp.o
.PHONY : src/feature_extractor.cpp.o

src/feature_extractor.i: src/feature_extractor.cpp.i
.PHONY : src/feature_extractor.i

# target to preprocess a source file
src/feature_extractor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_retrieval.dir/build.make CMakeFiles/image_retrieval.dir/src/feature_extractor.cpp.i
.PHONY : src/feature_extractor.cpp.i

src/feature_extractor.s: src/feature_extractor.cpp.s
.PHONY : src/feature_extractor.s

# target to generate assembly for a file
src/feature_extractor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_retrieval.dir/build.make CMakeFiles/image_retrieval.dir/src/feature_extractor.cpp.s
.PHONY : src/feature_extractor.cpp.s

src/knn.o: src/knn.cpp.o
.PHONY : src/knn.o

# target to build an object file
src/knn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_retrieval.dir/build.make CMakeFiles/image_retrieval.dir/src/knn.cpp.o
.PHONY : src/knn.cpp.o

src/knn.i: src/knn.cpp.i
.PHONY : src/knn.i

# target to preprocess a source file
src/knn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_retrieval.dir/build.make CMakeFiles/image_retrieval.dir/src/knn.cpp.i
.PHONY : src/knn.cpp.i

src/knn.s: src/knn.cpp.s
.PHONY : src/knn.s

# target to generate assembly for a file
src/knn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_retrieval.dir/build.make CMakeFiles/image_retrieval.dir/src/knn.cpp.s
.PHONY : src/knn.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... image_retrieval"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/distance_metrics.o"
	@echo "... src/distance_metrics.i"
	@echo "... src/distance_metrics.s"
	@echo "... src/feature_extractor.o"
	@echo "... src/feature_extractor.i"
	@echo "... src/feature_extractor.s"
	@echo "... src/knn.o"
	@echo "... src/knn.i"
	@echo "... src/knn.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

